# frozen_string_literal: true

source 'https://rubygems.org'

gem 'github', '~> 0.7.2'
gem 'github-markup', '~> 3.0', '>= 3.0.4'
gem 'octokit', '~> 4.0'
gem 'rack', '~> 2.2', '>= 2.2.2'
gem 'rest-client', '~> 2.1'
